version: "3.6"
services:
  solr:
    image: solr:${SOLR_TAG}
    expose:
      - "8983"
    entrypoint:
      - "docker-entrypoint.sh"
      - "solr-create"
      - "-c"
      - "collection1"
      - "-d"
      - "/config"
    volumes:
      - './solr/config:/config'

  db:
    image: mariadb:${DB_TAG}
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    expose:
      - "3306"
    volumes:
      - 'chirripo_database:/var/lib/mysql'
      - './mysql:/etc/mysql/conf.d'

  php:
    image: chirripo/php:${PHP_TAG}
    environment:
      - PHP_POST_MAX_SIZE=${PHP_POST_MAX_SIZE}
      - PHP_UPLOAD_MAX_FILESIZE=${PHP_UPLOAD_MAX_FILESIZE}
    user: "${CONTAINER_UID}"
    expose:
      - "9000"
    links:
      - db
      - solr
    volumes:
      - "${PROJECT_ROOT}:/var/www/html:delegated"

  nginx:
    image: nginx:${NGINX_TAG}
    ports:
      - "80"
    depends_on:
      - php
    links:
      - php
    volumes:
      - "${PROJECT_ROOT}:/var/www/html:delegated"
      - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"

volumes:
  chirripo_database:
    name: ${DB_VOLUME}_database
    external: false
