version: "3.6"
services:
  solr:
    image: solr:${SOLR_TAG}
    container_name: ${PROJECT_NAME}_solr
    ports:
      - "${PORT_PREFIX}83:8983"
    entrypoint:
      - "docker-entrypoint.sh"
      - "solr-create"
      - "-c"
      - "collection1"
      - "-d"
      - "/config"
    labels:
      - traefik.http.routers.solr-${PROJECT_NAME}.rule=Host(`solr.${VIRTUAL_HOST}`)
      - traefik.http.services.solr-${PROJECT_NAME}.loadbalancer.server.port=8983
      - traefik.http.routers.solr-ssl-${PROJECT_NAME}.rule=Host(`solr.${VIRTUAL_HOST}`)
      - traefik.http.routers.solr-ssl-${PROJECT_NAME}.tls=true
    volumes:
      - './solr/config:/config'
    networks:
      - internal
      - chirripo_proxy
networks:
  chirripo_proxy:
    external: true
  internal:
    external: false
